config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:index]

  # devise_for :users
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/privacy_policy' => 'pages#privacy_policy'

  unauthenticated :user do
    root to: 'pages#index'
    get '/coins' => 'crypto_graphs#index'
  end
  get 'all_users' => 'users#all_users'
  authenticated :user do
    root to: "pages#home", as: "authenticated_root"
    get '/home' => 'pages#home'
    get '/user/:id' => 'pages#profile'
    get '/coins' => 'crypto_graphs#index'
    patch '/update_avatar' => 'users#update_avatar'
    get '/cropper' => 'users#crop'
    resources :relationships, only: [:index, :create]

    resources :phone_verification, only: %i[index] do
      post :verify_pin, to: 'phone_verification#verify_pin', via: :post
    end
  end

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  match 'retweet_modal', to: 'retweet#open_modal', via: :get

  resources :relationships, only: [:create, :destroy]
  resources :posts
  post '/search' => 'posts#search'

  get '/explore' => 'pages#explore'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  respond_to :js

  def like
    @user = current_user
    @post = Post.find(params[:post_id])
    @user.like!(@post)
  end

  def unlike
    @user = current_user
    @like = @user.likes.find_by_post_id(params[:post_id])
    @post = Post.find(params[:post_id])
    @like.destroy!
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_button.html.haml
- if current_user.like?(post)
  -# = button_to "Unlike", unlike_path(post_id: post.id), remote: true, method: :delete
  = link_to(unlike_path(post_id: post.id), remote: true, method: :delete, style: "text-decoration: none;") do
    %i.fa.fa-thumbs-up
    = post.likes.count
- else
  -# = button_to "like", like_path(post_id: post.id), remote: true
  = link_to(like_path(post_id: post.id),  remote: true, method: :post, style: "text-decoration: none;") do
    %i.fa.fa-thumbs-up{style: "color: grey"}
  - if post.likes.count > 0
    = post.likes.count

app/views/likes/like.js.erb
$('div#<%= dom_id(@post) %>').html('<%= j render partial: "button", locals: {post: @post} %>');

app/views/likes/unlike.js.erb
$('div#<%= dom_id(@post) %>').html('<%= j render partial: "button", locals: {post: @post} %>');