config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:index]

  # devise_for :users
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/privacy_policy' => 'pages#privacy_policy'

  unauthenticated :user do
    root to: 'pages#index'
    get '/coins' => 'crypto_graphs#index'
  end
  get 'all_users' => 'users#all_users'
  authenticated :user do
    root to: "pages#home", as: "authenticated_root"
    get '/home' => 'pages#home'
    get '/user/:id' => 'pages#profile'
    get '/coins' => 'crypto_graphs#index'
    patch '/update_avatar' => 'users#update_avatar'
    get '/cropper' => 'users#crop'
    resources :relationships, only: [:index, :create]

    resources :phone_verification, only: %i[index] do
      post :verify_pin, to: 'phone_verification#verify_pin', via: :post
    end
  end

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  match 'retweet_modal', to: 'retweet#open_modal', via: :get

  resources :relationships, only: [:create, :destroy]
  resources :posts
  post '/search' => 'posts#search'

  get '/explore' => 'pages#explore'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  mount_uploader :resume, ResumeUploader
  enum role: [:user, :moderator]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :email, :password, :remember_me, :avatar, :avatar_cache, :remove_avatar
  # validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar
  validates_uniqueness_of :phone_number, allow_blank: true, allow_nil: true
  validates :phone_number, phone: { possible: false, allow_blank: true, types: [:mobile] }
  has_many :posts, dependent: :destroy # remove a user's posts if his account is deleted.
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :likes, dependent: :destroy
  # has_many :posts, through: :likes

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  after_create :default_avatar
  after_create :moderator_email
  before_save :unverify
  has_many :notifications, foreign_key: :recipient_id

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  def moderator_email
    if self.moderator?
      UserMailer.moderator_signup_email(self).deliver
    end
  end

  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end

  # helper methods
  def default_avatar
    self.update(avatar: File.open(File.join(Rails.root, '/public/avatar.png')))
  end

  # follow another user
  def follow(other)
   active_relationships.create(followed_id: other.id)
  end

  # unfollow a user
  def unfollow(other)
   active_relationships.find_by(followed_id: other.id).destroy
  end

  # is following a user?
  def following?(other)
   following.include?(other)
  end

  # creates a new like row with post_id and user_id
  def like!(post)
    self.likes.create!(post_id: post.id)
  end

  # destroys a like with matching post_id and user_id
  def unlike!(post)
    like = self.likes.find_by_post_id(post.id)
    like.destroy!
  end

  # returns true or false if a post is liked by user
  def like?(post)
    self.likes.find_by_post_id(post.id)
  end

  def unverify
    if self.changed.include? 'phone_number'
      self.phone_verified = false
      self.phone_verification_pin = nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def all_users
    respond_to do |format|
      format.json { render json: {response: User.all.pluck(:username)} }
    end
  end

  def update_avatar
    @user = current_user
    if @user.update_attributes(user_params)
      if params[:user][:avatar].present?
        render :cropper
      else
        redirect_to :root, notice: "Successfully updated user."
      end
    else
      render :new
    end
  end

  def crop
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar, :crop_x, :crop_y, :crop_w, :crop_h)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/crop.html.haml
-# %center
-#   %h1 Crop Avatar
-#   = image_tag @user.avatar.url(:large), id: "cropbox"
-#   %h4 Preview
-#   %div{:style => "width:100px; height:100px; overflow:hidden"}
-#     = image_tag @user.avatar.url(:large), :id => "preview"
-#   = form_for @user, url: update_avatar_path do |f|
-#     - %w[x y w h].each do |attribute|
-#       = f.hidden_field "crop_#{attribute}"
-#     %br/
-#     .actions
-#       %a{ :href => "/", class: "btn btn-danger" }
-#         cancel
-#       = f.submit "Crop", class: 'btn btn-primary'
-#     %br/
/ Modal
#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %center
          %h4#exampleModalLabel.modal-title Crop Avatar
        -# %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button", :href => "/"}
        -#   %span{"aria-hidden" => "true"} ×
      .modal-body
        %center
        = image_tag @user.avatar.url(:large), id: "cropbox"
        %h4 Preview
        %div{:style => "width:100px; height:100px; overflow:hidden"}
          = image_tag @user.avatar.url(:large), :id => "preview"
        = form_for @user, url: update_avatar_path do |f|
          - %w[x y w h].each do |attribute|
            = f.hidden_field "crop_#{attribute}"
          %br/
          .actions
            %a{ :href => "/", class: "btn btn-danger" }
              cancel
            = f.submit "Crop", class: 'btn btn-primary'
          %br/
      .modal-footer

:javascript
  $(document).ready( function() {
    $('#exampleModal').modal('show');
  });