config/routes.rb
Rails.application.routes.draw do

  resources :notifications, only: [:index]

  # devise_for :users
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/privacy_policy' => 'pages#privacy_policy'

  unauthenticated :user do
    root to: 'pages#index'
    get '/coins' => 'crypto_graphs#index'
  end
  get 'all_users' => 'users#all_users'
  authenticated :user do
    root to: "pages#home", as: "authenticated_root"
    get '/home' => 'pages#home'
    get '/user/:id' => 'pages#profile'
    get '/coins' => 'crypto_graphs#index'
    patch '/update_avatar' => 'users#update_avatar'
    get '/cropper' => 'users#crop'
    resources :relationships, only: [:index, :create]

    resources :phone_verification, only: %i[index] do
      post :verify_pin, to: 'phone_verification#verify_pin', via: :post
    end
  end

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete

  match 'retweet_modal', to: 'retweet#open_modal', via: :get

  resources :relationships, only: [:create, :destroy]
  resources :posts
  post '/search' => 'posts#search'

  get '/explore' => 'pages#explore'
end

app/views/layouts/_nav.html.erb
<!-- we will render seperate nav bars depending on if the user is signed in or not. -->
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %li
        %a{:href => "/"}
          %h1.brand-navbar{:src => "/logo.png"} The People's Voice
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button", style: "margin-top: -1%;"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %center
            %h1.display-4{style: "font-size: 25px; margin-top: 10px;"} CoinCobbler
      %center
        %ul.nav.navbar-nav.navbar-right
          %li.signin
            %button
              .fa.fa-user.fa-lg
              = link_to('Sign In', new_user_session_path)
          %li.signup
            Join Now:
            %button
              = link_to('Sign Up', new_user_registration_path)

app/views/layouts/_nav_user.html.haml
%a{:name => "top"}
%nav.navbar.navbar-default#nav-user
  .container-fluid.container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %li
        %a{:href => "/"}
          %h1.brand-navbar{:src => "/logo.png"} The People's Voice
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button", style: "margin-top: -1%;"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / %img.navbar-brand{:src => "/icon_colored.png", class: 'footer_icon'}/
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %center
        %ul.nav.navbar-nav
          %li
            %a{:href => "/home"} Home
          %li
            %a{:href => "/explore"} Explore
          %li
            %a{:href => "/coins"} Coins
        %ul.nav.navbar-nav.navbar-right
          %li
            #nav-search
              .form-group
                =form_tag(controller: '/posts' , action: :search) do
                  .search_field
                    =text_field_tag :search_field, nil,placeholder: 'search'

                  / %input.form-control{:placeholder => "Search Coins", :type => "text"}/
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %img#nav_profile_image.rounded-img{height: "25px", src: "#{current_user.avatar.url(:thumb)}", width: "25px"}/
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "/user/#{current_user.username}"} Profile
              %li.divider{:role => "separator"}
              %li= link_to('Settings', edit_user_registration_path)
              %li.divider{:role => "separator"}
              %li= link_to('Log Out', destroy_user_session_path, :method => :delete)

          %li.dropdown{ 'data-behavior': 'notifications' }
            %a.dropdown-toggle{ 'data-toggle': 'dropdown', role: 'button', 'aria-expanded': false }
              %span.glyphicon.glyphicon-bell
              %span.badge{ 'data-behavior': 'unread-count' }
              %span.caret

            %ul#notifications.dropdown-menu{ 'data-behavior': 'notification-items' }
              - if current_user.notifications.unread.empty?
                %li.dropdown-header.text-uppercase No new notifications
              -else
                %li.dropdown-header.text-uppercase Notifications

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Coin Cobbler
    = favicon_link_tag asset_path('faviconxyz.ico'), :rel => 'icon', :type => "image/x-icon"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css", :rel => "stylesheet"}/
    %script{:src => "//cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"}
    %script{:src => "https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"}\
    %link{:href => "https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css", :rel => "stylesheet"}/


  %body
    = render '/layouts/nav'
    - if params[:id] != nil
      - @url = '/user/' + params[:id]
      - user_param = User.find_by_username(params[:id])
      - if current_page?(@url)
        .container
          .row
            .col-sm-12{:style => "background-color: white;"}
              .container
                .col-sm-3  
                .col-sm-6{:style => "margin-top: 5px"}
                  .col-sm-2{:style => "font-size: 100%; opacity: 0.7;"}
                    POSTS
                    %br/
                    %h6{:style => "color: #0084B4; font-size: 150%;"}= user_param.posts.count
                  .col-sm-2{:style => "font-size: 100%; opacity: 0.7;"}
                    FOLLOWERS
                    %br/
                    %h6{:style => "color: #0084B4; font-size: 150%;"}= user_param.followers.count
                  - if current_user.username == params[:id]
                    .col-sm-8{:style => "text-align: right; margin-top: 5px;"}
                      %a{:href => "/users/edit"}
                        %li.btn.btn-default{:style => "color: grey; opacity: 0.8; font-weight: bold;", :type => "button"} EDIT PROFILE
                  - else
                    - if current_user.following?(User.find_by(username: params[:id]))
                      .col-sm-8{:style => "text-align: right; margin-top: 5px;"}
                        = link_to 'Unfollow', relationship_path(id: User.find_by(username: params[:id]).id), method: :delete, class: "btn btn-default"
                    - else
                      .col-sm-8{:style => "text-align: right; margin-top: 5px;"}
                        = link_to 'Follow', relationships_path(followed_id: User.find_by(username: params[:id]).id), :method => :post, class: "btn btn-primary"

    - if !current_user
      .col-sm-12{style: 'background-color: #36405F;'}
        .col-sm-5
        %span.notice= notice
        %span.alert= alert
      = stylesheet_link_tag 'guest_user_layout', media: 'all', 'data-turbolinks-track' => true
      - coin_percentages = coin_24h_volume_and_price
      .search-background
        .col-md-12
          .col-md-2
          .col-md-8
            = form_tag(controller: '/posts' , action: :search) do
              %i.search-field-icon.fa.fa-search.fa-lg
              = text_field_tag :search_field, nil,placeholder: 'Symbol or @username', class: 'home_page_search'
          .col-md-2
        %center.col-md-12
          .add
            Advertisement Banner

      .slider
        - Post.present_values_actual.each do |value|
          .ticker__item
            %span
              = link_to image_tag("#{value.downcase}.png"), "/coins?type=#{value}", style: "width:30px; height:30px; margin-right: 0.5rem;"
              = value
              %text.text-medium
                = coin_percentages[value][:price]
              - if coin_percentages[value][:volume] < 0
                %i.fa.fa-sort-down.fa-sm.red
                %text.text-small
                  = coin_percentages[value][:volume].abs
                  = '%'
              - else
                %i.fa.fa-sort-up.fa-sm.green
                %text.text-small
                  = coin_percentages[value][:volume]
                  = '%'
      .slider_description
        Get Funded — Funding Stream
      .slider_funding_stream
        - 5.times do
          - ['Business', 'Medical', 'Charity', 'Animal'].each do |value|
            .ticker__item
              %span
                %img.rounded-img{:height => "30px", :src => "#{User.first.avatar.url(:thumb)}", :width => "30px"}/
                = image_tag "thermometer.png", style: "width:30px; height:30px; margin-right: 0.5rem;"
                %center{style: 'margin-left: -56%; font-size: 1.3rem;'}
                  %br/
                  %br/
                  = value
                  Funded
      .slider_description
        Share Your Thoughts — Knowledge Stream
      .slider_knowledge_stream
        - Post.present_values_actual.each do |value|
          .ticker__item{style: 'font-size: 1.6rem'}
            %span
              %a{href: "/coins?type=#{value}"}
                %span.trending-tags
                  %b{:style => "color: grey; font-size: 1.6rem"}
                    |
                  = value.upcase

      -# Side Bars Start Here --------------------
      .container
        .col-md-12
          .col-md-12.white-pannel
            = yield
    - else
      .col-sm-12
        .col-sm-5
        %span.notice= notice
        %span.alert= alert
      .container
        .col-md-12
          .col-md-3
            .panel.panel-default
              .panel-footer
                .row
                  - if user_param
                    .col-sm-2
                      %img.rounded-img.home-avatar{:height => "50px", :src => "#{user_param.avatar.url(:thumb)}", :width => "50px"}/
                    .col-sm-10
                      %h4{:style => "text-align: center;"}= user_param.username
                    .col-sm-12{:style => "margin-top: 10px;"}
                      .col-sm-6{:style => "font-size: 80%; opacity: 0.7;"}
                        POSTS
                        %br/
                        %h6{:style => "color: #0084B4; font-size: 200%;"}= user_param.posts.count
                      .col-sm-6{:style => "font-size: 80%; opacity: 0.7;"}
                        FOLLOWERS
                        %br/
                        %h6{:style => "color: #0084B4; font-size: 200%;"}= user_param.followers.count

                  - else
                    .col-sm-2
                      %img.rounded-img.home-avatar{:height => "50px", :src => "#{current_user.avatar.url(:thumb)}", :width => "50px"}/
                    .col-sm-10
                      %h4{:style => "text-align: center;"}= current_user.username
                    .col-sm-12{:style => "margin-top: 10px;"}
                      .col-sm-6{:style => "font-size: 80%; opacity: 0.7;"}
                        POSTS
                        %br/
                        %h6{:style => "color: #0084B4; font-size: 200%;"}= current_user.posts.count
                      .col-sm-6{:style => "font-size: 80%; opacity: 0.7;"}
                        FOLLOWERS
                        %br/
                        %h6{:style => "color: #0084B4; font-size: 200%;"}= current_user.followers.count

            .panel.panel-default
              .panel-body
                %h5{:style => "color: grey; font-size: 125%;"} Trends
                - Tag.all.order('post_count desc').each do |t|
                  %a{href: "/coins?type=#{t.name.downcase}"}
                    $
                    = t.name
                  %br/
                  %br/

          .col-md-7
            = yield
          .col-md-2
            .panel.panel-default
              .panel-body
                %h5{:style => "color: grey; font-size: 125%;"} Who to follow
                - User.where.not(id: current_user.id).last(5).each do |u|
                  %p{:style => "font-weight: bold; opacity: 0.85;"}
                    %a{:href => "/user/#{u.username}"}= u.username
            .panel.panel-default
              .panel-body
                %center
                  %p{:style => "opacity: 0.5; font-size: 90%;"} © 2018 Coin Cobbler
                  %a{:href => "/privacy_policy", style: "opacity: 0.9; font-size: 100%; text-decoration: none;", target: "_blank"}
                    Privacy Policy